### ISSUE TITLE
ISLa stops producing syntactically valid inputs after 10 iterations

### ISSUE THREAD

**Issue by michaelmera** [rindPHI/isla#1]
ISLa version: 
```console
$ python -c 'import isla; print(isla.__version__)'
0.10.0
```

Here is the file for reproducing the problem:
```Python
# isla_vector.py
from isla.type_defs import Grammar
from isla.solver import ISLaSolver

GRAMMAR: Grammar = {
    "<start>": ["<point>"],
    "<point>": ["<x> <y> <z>"],
    "<x>": ["<digit>"],
    "<y>": ["<digit>"],
    "<z>": ["<digit>"],
    "<digit>": ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9"],
}

solver = ISLaSolver(GRAMMAR,
    """
    (<= (+ (^ str.to.int(<point>.<x>) 2)
           (^ str.to.int(<point>.<y>) 2)
           (^ str.to.int(<point>.<z>) 2))
        900)
    """
)

if __name__ == '__main__':
    for _ in range(20):
        print(next(solver.solve()))

    print('done')
```

The output is:
```console
$ python isla_vector.py
0 0 0
1 8 8
9 4 2
3 9 3
4 1 6
2 5 4
6 2 1
8 6 5
5 7 7
7 3 9
0
0
0
0
0
0
0
0
0
0
```
It seems to me that the outputs after the 10th execution are not even syntactically valid for the grammar given.

**Comment by rindPHI** [comment]
Hi Michael!

Two things: The `solver.solve()` function returns an iterator, so you should not call `solver.solve()` repeatedly, but store the iterator and call `next` on the iterator object.

You can, however, use the `fuzz()` method that works exactly as you want to use it: `solver.fuzz()` returns the next input (no `next` call required).

Now, the second thing: `fuzz()` (and similarly `solve()`) may return an integer to signal a timeout of that no more solutions can be found, see its documentation:

```
Attempts to compute a solution to the given ISLa formula. Returns that solution, if any.
This function can be called repeatedly to obtain more solutions until `ISLaSolver.TIMEOUT`
or `ISLaSolver.UNSAT` is returned. After that, only `TIMEOUT` or `UNSAT` will be returned
at each call.

The timeout can be controlled by the `timeout_seconds` constructor parameter.

:return: A solution for the ISLa formula passed to the `ISLaSolver`, or `ISLaSolver.TIMEOUT` (if
a timeout occurred) or `ISLaSolver.UNSAT` if no more solutions or none at all could be found.
```

The `0` value signals that no more solutions can be found (`ISLaSolver.UNSAT`).

This was in fact the issue that Martin mentioned in our meeting yesterday, he would like some object returned instead of an Integer constant to avoid this confusion. I will find a stable sensible interface for ISLa 1.0.0.

**Comment by martineberlein** [comment]
The `0`s after the 10th iteration correspond to the `ISLaSolver.UNSAT`, and are not a DerivationTree.

**Comment by michaelmera** [comment]
Hi @rindPHI and @martineberlein. Thanks for the quick answers! I now understand what's happening. :flushed:

The loop is directly copy-pasted from the [tutorial](https://www.fuzzingbook.org/beta/html/FuzzingWithConstraints.html#Synopsis), so you might want to change that.

**Comment by rindPHI** [comment]
Ooops yes. ISLa is evolving quickly 😵‍💫
