### ISSUE TITLE
Solver outputs solution for unsatisfiable formula with three quantifiers

### ISSUE THREAD

**Issue by mojung** [rindPHI/isla#57]
**Description**

The solver outputs a solution for an unsatisfiable formula with three quantifiers.

**Steps to reproduce**

Please execute the code snippet below.

````python
from isla.language import parse_isla
from isla.isla_predicates import AFTER_PREDICATE
from isla.solver import ISLaSolver

grammar = {
    '<start>': ['<a_or_b> <c>'],
    '<a_or_b>': ['<a>', '<b>'],
    '<a>': ['a'],
    '<b>': ['b'],
    '<c>': ['c']
}

constraint = parse_isla(
    """
    forall <a> a:
        forall <b> b:
            forall <c> c:
                (not after(c, a) and not after(c, b))
    """,
    grammar,
    structural_predicates={AFTER_PREDICATE}
)

solver = ISLaSolver(grammar, constraint)

for _ in range(5):
    print(solver.solve().to_string())
````

**Expected behavior**

Since the constraint is unsatisfiable, the expected output would be `StopIteration`, but instead it is `b c`.

**Tested ISLa version**

ISLa version 1.10.4

**Additional information**

For the following (equivalent) constraint, the solver output is as expected, i.e., `StopIteration`:

````python
constraint = parse_isla(
    """
    forall <c> c:
        ((forall <a> a:
            (not after(c, a)))
        and
        (forall <b> b:
            (not after(c, b))))
    """,
    grammar,
    structural_predicates={AFTER_PREDICATE}
)
````

**Comment by rindPHI** [comment]
**This is desired behavior.**

In the above formula, one of the quantifiers is *vacuously satisfied* (since there *is no* b or c in all cases), which renders the formula trivially true. This does not happen in your second formula. They are not equivalent. You can even ask ISLa for a counterexample of their equivalence; `a c` is one.

Vacuous satisfaction means that there is no instantiation for a quantifier; thus, it holds for all instantiations. It's like in "all cows born blue can solve the Halting problem," which is indeed true since no cows are born blue.

Closing this; feel free to ask back in case of questions.

**Comment by rindPHI** [comment]
If you change the grammar to

```python
grammar = {
            '<start>': ['<a_and_b> <c>'],
            '<a_and_b>': ['<a><b>'],
            '<a>': ['a'],
            '<b>': ['b'],
            '<c>': ['c']
        }
```

(and update the constraint accordingly), you get a `StopIteration`.
